# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'RoomyAppSwiftyCamp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RoomyAppSwiftyCamp
	pod 'Alamofire', '~> 4.7'
	pod 'Kingfisher', '~> 5.0'
	pod 'ObjectMapper', '~> 3.4'


end
